# Generated by Django 5.1.7 on 2025-03-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vartotojas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vardas', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sukurta', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
