# Generated by Django 5.1.7 on 2025-03-26 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registracija', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registracija',
            old_name='skurta',
            new_name='sukurta',
        ),
    ]
