# Generated by Django 5.1.7 on 2025-03-30 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vardas', models.CharField(max_length=100)),
                ('pavarde', models.CharField(max_length=100)),
                ('gimimo_metai', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(max_length=200)),
                ('isleidimo_data', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('autorius', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='katalogas.author')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
